-- Gestionale Bar — migrazione 0006 — SOSTITUITA, NON ESEGUIRE
--
-- Questo file conteneva la prima bozza dello schema di magazzino. Non è mai
-- stato eseguito da nessuna parte, ed è stato riscritto in
-- `0020_magazzino.sql`. Resta qui vuoto invece di sparire perché è citato in
-- `05-ROADMAP.md` T-02 e in `06-SETUP-SUPABASE.md` §4, e un file che manca
-- fa cercare per mezz'ora una cosa che non c'è.
--
-- CHE COSA È CAMBIATO, E PERCHÉ.
--
-- La bozza teneva le quantità in `numeric(10,3)`. Dentro Postgres sarebbe
-- stato esatto; il problema comincia quando quel numero esce. PostgREST lo
-- consegna a JavaScript, dove il decimale esatto non esiste — 0,1 + 0,2 non
-- fa 0,3. Un caffè scarica 7 g di grani, duecento caffè al giorno per un mese
-- sono seimila somme, e la giacenza comincia a finire con ,00000000004.
-- Poi la si confronta con l'inventario contato a mano e non torna mai.
--
-- È la stessa ragione per cui il denaro sta in centesimi interi (DEC-04).
-- In `0020` le quantità sono **interi in millesimi**.
--
-- Sono cambiate anche altre tre cose:
--   - i segni sono vincolati al tipo di movimento (un "carico" negativo non
--     si può più scrivere);
--   - i movimenti sono immutabili come tutti gli altri (DEC-03);
--   - lo scarico automatico non può far fallire l'inserimento di una riga di
--     conto, cioè non può far perdere una vendita.
--
-- Lo stesso è successo a `0005_fase2_cassa.sql`, sostituito da `0016`.
